"""Create2

Revision ID: e97e501b56d6
Revises: b479a1e3d057
Create Date: 2025-05-12 23:39:38.425415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97e501b56d6'
down_revision: Union[str, None] = 'b479a1e3d057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipmentorders', sa.Column('equipment_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'equipmentorders', 'equipments', ['equipment_id'], ['id'])
    op.drop_constraint('equipments_equipmentorders_id_fkey', 'equipments', type_='foreignkey')
    op.drop_column('equipments', 'equipmentorders_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('equipmentorders_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('equipments_equipmentorders_id_fkey', 'equipments', 'equipmentorders', ['equipmentorders_id'], ['id'])
    op.drop_constraint(None, 'equipmentorders', type_='foreignkey')
    op.drop_column('equipmentorders', 'equipment_id')
    # ### end Alembic commands ###
